apiVersion: v1
kind: Service
metadata:
  name: node-project-service
  namespace: node-project
  labels:
    app: node-project
spec:
  type: NodePort
  ports:
  - name: http
    protocol: TCP
    port: 3000
  selector:
    app: node-project
